spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/pams_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver