spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pams_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQLDialect # Added this line

  sql:
    init:
      mode: always

axon:
  eventhandling:
    processors:
      appointment:
        mode: tracking
      default:
        mode: tracking

  axonserver:
      enabled: false