version: '3.8'

services:
  mysql:
    image: mysql:5.7.20
    container_name: pams_mysql
    volumes:
      - ./data/mysql/:/var/lib/mysql/
      - ./data/backup:/opt
    environment:
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=pams_db

    ports:
      - 3306:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8 --explicit_defaults_for_timestamp --max_allowed_packet=3G

