name: Build & Deploy Patient Appointment Management System
on:
  push:
    branches:
      - main
jobs:
  build-deploy:
    name: Build & Deploy Patient Appointment Management System
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Unit Tests
        run: mvn -B test --file pom.xml -Dspring.profiles.active=test

      - name: Build the Application
        run: |
          mvn clean
          mvn -B package --file pom.xml -DskipTests

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/patient-appointment:$(date +'%Y%m%d%H%M%S')

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/patient-appointment:$(date +'%Y%m%d%H%M%S')