name: Build & Deploy Patient Appointment Management System

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build & Deploy Patient Appointment Management System
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Unit Tests
        run: mvn -B test --file pom.xml

      - name: Build the Application
        run: |
          mvn clean
          mvn -B package --file pom.xml

        

        



