name: Build & Deploy Patient Appointment Management System

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build & Deploy Patient Appointment Management System
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7.20
        env:
          MYSQL_ROOT_PASSWORD: ""
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
          MYSQL_DATABASE: pams_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Wait for MySQL
        run: |
          while ! mysqladmin ping -h"127.0.0.1" --silent; do
            sleep 1
          done

      - name: Unit Tests
        run: mvn -B test --file pom.xml

        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/pams_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true



      - name: Build the Application
        run: |
          mvn clean
          mvn -B package --file pom.xml

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/patient-appointment:$(date-'%Y%m%d%H%M%S')

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/patient-appointment:$(date-'%Y%m%d%H%M%S')






        

        



